library loadie;
import 'dart:async';
import 'dart:html';
import 'dart:convert';

// add extentions to this list to allow the loading of non-standard text files.
List <String> textExtensions = 
[
 'txt'
];

// add extentions to this list to allow the loading of non-standard json files.
List <String> jsonExtensions = 
[
 'json'
];

// image extentions cannot be changed.
final List <String> imageExtensions = 
[
 'svg',
 'png',
 'jpg',
 'jpeg',
 'gif',
 'bmp'
];

// audio extentions cannot be changed.
final List <String> audioExtensions = 
[
 'mp3',
 'ogg'
];


class Asset{
  var _asset;
  bool loaded = false;
  String uri;
  
  Asset(this.uri){}
  
  Future load(){
    Completer c = new Completer();
    if (loaded == false){

      // loads ImageElements into memory
      for (String ext in imageExtensions)
      {
        if (uri.endsWith('.' + ext))
        {
          this._asset = new ImageElement()
          ..src = uri
          ..classes.add('!-autogenerated-!');
          _asset.onLoad.listen((_) {loaded = true;c.complete(this);});
        }
      }
      
      // loads AudioElements into memory
      for (String ext in audioExtensions)
      {
        if (uri.endsWith('.' + ext))
        {
          AudioElement audio = new AudioElement()
          ..src = uri
          ..classes.add('!-autogenerated-!');
          AudioElement a = document.body.append(audio);
          audio.onCanPlay.listen((_) {this._asset= audio;_asset;loaded = true;c.complete(this);});
        }
      }
      
      // loads simple text files as a string.
      for (String ext in textExtensions)
      {
        if (uri.endsWith('.' + ext))
        {
          HttpRequest.getString(uri).then
          ((String string)  {
            _asset = string;
            loaded = true;
            c.complete(this);
            });
        }
      }
      
      // Returns a decoded object from a json file
      for (String ext in jsonExtensions)
      {
        if (uri.endsWith('.' + ext))
        {
          HttpRequest.getString(uri).then
          ((String string)  {
            _asset =  JSON.decode(string);
            loaded = true;
            c.complete(this);
            });
        }
      }

      return c.future;
    }
  
  }  

  
  get(){
    if (loaded == false)
      throw('Asset not yet loaded!');
    else
    return _asset;
  }
}