library loadie;
import 'dart:async';
import 'dart:html';
import 'dart:convert';


Map <String,Asset> ASSET = {};


// add extentions to this list to allow the loading of non-standard text files.
List <String> textExtensions = 
[
 'txt'
];

// add extentions to this list to allow the loading of non-standard json files.
List <String> jsonExtensions = 
[
 'json'
];

// image extentions cannot be changed.
final List <String> imageExtensions = 
[
 'svg',
 'png',
 'jpg',
 'jpeg',
 'gif',
 'bmp'
];

// audio extentions cannot be changed.
final List <String> audioExtensions = 
[
 'mp3',
 'ogg'
];



// a helper class for loading bars and such.
// the callback function will be provided with the percent of the batch that is loaded.
class Batch {
  List _toLoad = [];
  int _percentDone = 0;
  Batch(List <Asset> toLoad){this._toLoad = toLoad;}
  Future<List <Asset> > load(Function callback){
    int percentEach = 100~/_toLoad.length; 
   
    // creates a list of Futures
    List <Future> futures = [];
    for (Asset asset in _toLoad)
       {
     futures.add(asset.load().whenComplete((){
       // Broadcast that we loaded a file.
       _percentDone += percentEach;
       callback(_percentDone);}
     ));
       }     
  
    return Future.wait(futures);
  }
}



class Asset{
  var _asset;
  bool loaded = false;
  String _uri;
  
  String name;
  
  Asset(String uri){this._uri = uri;}
  
  Future <Asset> load(){
    name = _uri.split('/')[_uri.split('/').length - 1].split('.')[0];
    Completer c = new Completer();    
    if (loaded == false){

      // loads ImageElements into memory
      for (String ext in imageExtensions)
      {
        if (_uri.endsWith('.' + ext))
        {
          this._asset = new ImageElement()
          ..src = _uri
          ..classes.add('!-autogenerated-!');
          _asset.onLoad.listen((_) {
            ASSET[name] = this;
            loaded = true;c.complete(this);
            });
        }
      }
      
      // loads AudioElements into memory
      for (String ext in audioExtensions)
      {
        if (_uri.endsWith('.' + ext))
        {
          AudioElement audio = new AudioElement()
          ..src = _uri
          ..classes.add('!-autogenerated-!');
          AudioElement a = document.body.append(audio);
          audio.onCanPlay.listen((_) {
            ASSET[name] = this;
            this._asset= audio;
            loaded = true;
            c.complete(this);});
        }
      }
      
      // loads simple text files as a string.
      for (String ext in textExtensions)
      {
        if (_uri.endsWith('.' + ext))
        {
          HttpRequest.getString(_uri).then
          ((String string)  {
            _asset = string;
            loaded = true;
            ASSET[name] = this;
            c.complete(this);
            });
        }
      }
      
      // Returns a decoded object from a json file
      for (String ext in jsonExtensions)
      {
        if (_uri.endsWith('.' + ext))
        {
          HttpRequest.getString(_uri).then
          ((String string)  {
            ASSET[name] = this;
            _asset =  JSON.decode(string);
            loaded = true;
            c.complete(this);
            });
        }
      }

      return c.future;
    }
  
  }  

  
  get(){
    if (loaded == false)
      throw('Asset not yet loaded!');
    else
    return _asset;
  }
}